baseURL: "https://dongyuhui.info"
languageCode: "zh-CN"
title: "光合日记"
pygmentsstyle: 'monokai'
theme: "hugo-theme-novela"
paginate: 10

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
defaultContentLanguage: zh-cn

social:
  github: "https://github.com/DongYuHui"
  instagram: "https://instagram.com/dongxiaohui827"
  weibo: "https://weibo.com/mandaoxiaohui"

permalinks:
    post: /post/:slug/
    page: /:slug/

taxonomies:
  author: authors

params:
  footerTitle: "DongYuHui"
  footerRecord: "浙ICP备20005422号-1"
  showAbout: true