baseURL: "https://dongyuhui.info"
languageCode: "zh-CN"
title: "光合日记"
pygmentsstyle: 'monokai'
theme: "hugo-theme-novela"

# Pagination settings
pagination:
  # Number of posts per page
  pagerSize: 10

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
defaultContentLanguage: zh-cn

permalinks:
    post: /post/:slug/
    page: /:slug/

taxonomies:
  author: authors

params:
  footerTitle: "DongYuHui"
  footerRecord: "浙ICP备20005422号-1"
  showAbout: true
  # social media
  social:
    - name: "GitHub"
      url: "https://github.com/DongYuHui"
    - name: "Instagram"
      url: "https://instagram.com/dongxiaohui827"
    - name: "Weibo"
      url: "https://weibo.com/mandaoxiaohui"